### ISSUE TITLE
Should be a page to view official ping pong rules

### ISSUE THREAD

**Issue by jlholm** [ElixirCLE/CoverMyPingPong#4]
Game rules change per game. We should be following one set of "general" rules

**Comment by Serneum** [comment]
We use a simplified set of https://pongworld.com/table-tennis-sport/rules

Basically we just don't do the best of 3 or 5 because we play to 21 points.

1. A serve starts with the ball being tossed up at least 6 inches
  1a. If the ball touches the net during the serve, it is a Let and the serve is redone
2. Volley to see who serves first. The ball must be hit a minimum of 4 times
3. Alternate serves every 5 points
4. Play to 21
  4a. A player must win by 2 points
5. You cannot lose on a serve

**Comment by jlholm** [comment]
I agree with those. There are other rules that I do play by but they're a little more competitive.

Here is a very good ping pong channel w/ rules & tutorials: [PingSkills](https://www.youtube.com/user/pingskills)

Here is one of his videos going over a rule that I do play by: [Hitting the ball before it bounces?](https://www.youtube.com/watch?v=EDEHqkfigH0)

**Comment by Serneum** [comment]
We actually informally use a similar rule to what's in that video. Definitely add it

**Comment by jlholm** [comment]
Awesome, I'll do this page today

**Comment by jlholm** [comment]
Added rules page: #20
